#version 430

layout(local_size_x = 8, local_size_y = 8 , local_size_z = 1) in;
layout(rgba8, binding = 0) uniform image2D outputImage;


void main()
{

    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = imageLoad(outputImage, pixelCoords);

    if(pixelCoords.x > 100 && pixelCoords.x < 200 && pixelCoords.y > 100 && pixelCoords.y < 200)
        color.rgb = vec3(0.5f, 0.5f, 0.5f);
    imageStore(outputImage, pixelCoords, color);
}